package hibernate;
// Generated 06-jun-2018 14:30:57 by Hibernate Tools 5.3.0.Beta2

import java.math.BigDecimal;

/**
 * Detalleventa generated by hbm2java
 */
public class Detalleventa implements java.io.Serializable {

	private BigDecimal codigoArticulo;
	private BigDecimal cantidad;
	private BigDecimal precioUd;
	private BigDecimal codigoVenta;

	public Detalleventa() {
	}

	public Detalleventa(BigDecimal codigoArticulo, BigDecimal cantidad, BigDecimal precioUd, BigDecimal codigoVenta) {
		this.codigoArticulo = codigoArticulo;
		this.cantidad = cantidad;
		this.precioUd = precioUd;
		this.codigoVenta = codigoVenta;
	}

	public BigDecimal getCodigoArticulo() {
		return this.codigoArticulo;
	}

	public void setCodigoArticulo(BigDecimal codigoArticulo) {
		this.codigoArticulo = codigoArticulo;
	}

	public BigDecimal getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(BigDecimal cantidad) {
		this.cantidad = cantidad;
	}

	public BigDecimal getPrecioUd() {
		return this.precioUd;
	}

	public void setPrecioUd(BigDecimal precioUd) {
		this.precioUd = precioUd;
	}

	public BigDecimal getCodigoVenta() {
		return this.codigoVenta;
	}

	public void setCodigoVenta(BigDecimal codigoVenta) {
		this.codigoVenta = codigoVenta;
	}

}
