package hibernate;
// Generated 06-jun-2018 14:30:57 by Hibernate Tools 5.3.0.Beta2

import java.math.BigDecimal;
import java.sql.Blob;

/**
 * Producto generated by hbm2java
 */
public class Producto implements java.io.Serializable {

	private BigDecimal codigo;
	private Categoria categoria;
	private Editorial editorial;
	private String nombre;
	private Blob foto;
	private BigDecimal preciocoste;
	private BigDecimal pvp;

	public Producto() {
	}

	public Producto(BigDecimal codigo, String nombre, BigDecimal preciocoste, BigDecimal pvp) {
		this.codigo = codigo;
		this.nombre = nombre;
		this.preciocoste = preciocoste;
		this.pvp = pvp;
	}

	public Producto(BigDecimal codigo, Categoria categoria, Editorial editorial, String nombre, Blob foto,
			BigDecimal preciocoste, BigDecimal pvp) {
		this.codigo = codigo;
		this.categoria = categoria;
		this.editorial = editorial;
		this.nombre = nombre;
		this.foto = foto;
		this.preciocoste = preciocoste;
		this.pvp = pvp;
	}
	
	public Producto(BigDecimal codigo, Categoria categoria, Editorial editorial, String nombre,
			BigDecimal preciocoste, BigDecimal pvp) {
		this.codigo = codigo;
		this.categoria = categoria;
		this.editorial = editorial;
		this.nombre = nombre;
		this.preciocoste = preciocoste;
		this.pvp = pvp;
	}

	public BigDecimal getCodigo() {
		return this.codigo;
	}

	public void setCodigo(BigDecimal codigo) {
		this.codigo = codigo;
	}

	public Categoria getCategoria() {
		return this.categoria;
	}

	public void setCategoria(Categoria categoria) {
		this.categoria = categoria;
	}

	public Editorial getEditorial() {
		return this.editorial;
	}

	public void setEditorial(Editorial editorial) {
		this.editorial = editorial;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Blob getFoto() {
		return this.foto;
	}

	public void setFoto(Blob foto) {
		this.foto = foto;
	}

	public BigDecimal getPreciocoste() {
		return this.preciocoste;
	}

	public void setPreciocoste(BigDecimal preciocoste) {
		this.preciocoste = preciocoste;
	}

	public BigDecimal getPvp() {
		return this.pvp;
	}

	public void setPvp(BigDecimal pvp) {
		this.pvp = pvp;
	}

}
